############################## English ##############################
languageName: En ğŸ‡ºğŸ‡¸
languageCode: en-US
contentDir: content/english
weight: 1

# Language overrides
copyright: |-
  Made with â¤ï¸ in France & Proudly hosted on [Clever Cloud](https://clever-cloud.com)

  Copyright &copy; 2020-2021 Monki Projects.

params:
  description: Making apps and tools for the parkour â€” an urban sport â€” community.
