############################## EspaÃ±ol ##############################
languageName: Es ğŸ‡ªğŸ‡¸
languageCode: es-ES
contentDir: content/spanish
weight: 3

# Language overrides
copyright: |-
  Hecho con â¤ï¸ en Francia y orgullosamente alojado en [Clever Cloud](https://clever-cloud.com).

  Copyright &copy; 2020-2021 Monki Projects.

params:
  description: Aplicaciones y herramientas para la comunidad del parkour â€“ un deporte urbano.
