############################## FranÃ§ais ##############################
languageName: Fr ğŸ‡«ğŸ‡·
languageCode: fr-FR
contentDir: content/french
weight: 2

# Language overrides
copyright: |-
  Fait avec â¤ï¸ en France & FiÃ¨rement hÃ©bergÃ© chez [Clever Cloud](https://clever-cloud.com/).

  Copyright &copy; 2020-2021 Monki Projects.

params:
  description: Des applications et des outils pour la communautÃ© du parkour â€“ un sport urbain.
